# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CronoExport < Formula
  desc "CLI to export Cronometer nutrition, biometrics, and food log data as JSON"
  homepage "https://github.com/quantcli/crono-export-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quantcli/crono-export-cli/releases/download/v0.1.1/crono-export_darwin_amd64.zip"
      sha256 "9750d2f5a339b161c298da98eb6f0a576a03644f9111c5a483c7930fb8beae85"

      define_method(:install) do
        bin.install "crono-export"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quantcli/crono-export-cli/releases/download/v0.1.1/crono-export_darwin_arm64.zip"
      sha256 "05c8e735c9a3f6d4346f9ad3d56d08da5557dd177bee8d481a3954dc04bb3043"

      define_method(:install) do
        bin.install "crono-export"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantcli/crono-export-cli/releases/download/v0.1.1/crono-export_linux_amd64.zip"
      sha256 "5375d05d64de8f8c9a5452a798666c6971f0d0a9de67d5aaf2db6726a6dd9912"
      define_method(:install) do
        bin.install "crono-export"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantcli/crono-export-cli/releases/download/v0.1.1/crono-export_linux_arm64.zip"
      sha256 "fdf10eda6b5fb34ed9d057e138f4f97dda97f8d2550638e6b9b7f062a1eb9c20"
      define_method(:install) do
        bin.install "crono-export"
      end
    end
  end
end
