# This file was generated by GoReleaser. DO NOT EDIT.
cask "crono-export" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "be75aad9bbd9f91dd02c3cb313fc3a63116124a2c822b14b19d3e02d25e343dc"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_darwin_amd64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
    on_arm do
      sha256 "1b4aceaa19de3d6574cf3ecf2eb3b6752ef732d258b949f08eed5012a73b3ec7"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_darwin_arm64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "cdb8881e030882f7b2ecf8513c257b8eb5c1e468bb299c34f520a86bab90259b"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_linux_amd64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
    on_arm do
      sha256 "9e044e1d677f57ee510d7a2449160a0a2c90d174232851c025cc8ec88392736e"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_linux_arm64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
  end

  name "crono-export"
  desc "CLI to export Cronometer nutrition, biometrics, and food log data as JSON"
  homepage "https://github.com/quantcli/crono-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crono-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crono-export"]
    end
  end

  # No zap stanza required

end
