# This file was generated by GoReleaser. DO NOT EDIT.
cask "crono-export" do
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_darwin_amd64.zip",
        verified: "github.com/quantcli/crono-export-cli"
      sha256 "ed780a43222275f3d4614f15451b1518d4cee79e824ac0e90565d00fbb5923a6"
    end
    on_arm do
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_darwin_arm64.zip",
        verified: "github.com/quantcli/crono-export-cli"
      sha256 "7f646c62c2f8650735d17aa45a6ccd3ebf7cdc9e821416beeffea0c94d1ff0d1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_linux_amd64.zip",
        verified: "github.com/quantcli/crono-export-cli"
      sha256 "d7a82686e6b5398d4b8b2736f3c9ac0252dcb763c4ec741629d37a1ccd05150e"
    end
    on_arm do
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_linux_arm64.zip",
        verified: "github.com/quantcli/crono-export-cli"
      sha256 "8ea8655bb84f51f06f84734be52743cb75df72986e22756f9dae49080319891e"
    end
  end

  name "crono-export"
  desc "CLI to export Cronometer nutrition, biometrics, and food log data as JSON"
  homepage "https://github.com/quantcli/crono-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crono-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crono-export"]
    end
  end

  # No zap stanza required

end
