# This file was generated by GoReleaser. DO NOT EDIT.
cask "crono-export" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "64cf15e87956f7a5efa371f3061418c95515daf639fb61872ecc1cb2f0fd9e97"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_darwin_amd64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
    on_arm do
      sha256 "e1232472fcc393f3687bf1bae3c324da6cc4af578cd3775df10170c65a316eb7"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_darwin_arm64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "55761f992731aacbe5a87492adea9b64e0d3f9bb57dadbf554e86726988d9656"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_linux_amd64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
    on_arm do
      sha256 "9c3c1b2e9c662f575aec197cf0271274f98f8d5c8482823b115425f416cd9718"
      url "https://github.com/quantcli/crono-export-cli/releases/download/v#{version}/crono-export_linux_arm64.zip",
        verified: "github.com/quantcli/crono-export-cli"
    end
  end

  name "crono-export"
  desc "CLI to export Cronometer nutrition, biometrics, and food log data as JSON"
  homepage "https://github.com/quantcli/crono-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crono-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crono-export"]
    end
  end

  # No zap stanza required

end
