# This file was generated by GoReleaser. DO NOT EDIT.
cask "liftoff-export" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "73befe03f4f6d2956f41bf7313d6014d2e95648fa4f989bc585f51f84df4ee3f"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_darwin_amd64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
    on_arm do
      sha256 "cb621e57645c1e91b57cfd2e5a44d3d679f1fe0e17af444b243a80318eaee777"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_darwin_arm64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "34d6a51bf7bc35450c40fa1f007d6823197da6f2d43da10325b7e0afae83a73c"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_linux_amd64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
    on_arm do
      sha256 "9aaac28110393f003e101805c8ea236b97197138e56b2adc718e52ed90f57d07"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_linux_arm64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
  end

  name "liftoff-export"
  desc "CLI tool to export and analyze workout data from the Liftoff fitness app"
  homepage "https://github.com/quantcli/liftoff-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "liftoff-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/liftoff-export"]
    end
  end

  # No zap stanza required

end
