# This file was generated by GoReleaser. DO NOT EDIT.
cask "liftoff-export" do
  version "1.1.2"

  on_macos do
    on_intel do
      sha256 "0c773e7461c1fb02b00092e6cf40ca11b2313fc7dc0fd7714d61c0354e6153dc"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_darwin_amd64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
    on_arm do
      sha256 "a0f4650c3f8db6ffeb290b9b42f811de82cc1590418c1ab708450f07c309b2d0"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_darwin_arm64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "efddcf8f7a904feaf5c092d239badf72467e8e04913e91c35d5b5f1b88138f51"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_linux_amd64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
    on_arm do
      sha256 "6616c6c7b1d905b3da905bf9aa78db57af326cfeb73559ba36385144c7a9f4b6"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_linux_arm64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
  end

  name "liftoff-export"
  desc "CLI tool to export and analyze workout data from the Liftoff fitness app"
  homepage "https://github.com/quantcli/liftoff-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "liftoff-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/liftoff-export"]
    end
  end

  # No zap stanza required

end
