# This file was generated by GoReleaser. DO NOT EDIT.
cask "liftoff-export" do
  version "1.0.5"

  on_macos do
    on_intel do
      sha256 "c3cec45822c30dde07fa1e019005ce1b2e4a2def0ae2065ec963a1ae0feedd8c"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_darwin_amd64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
    on_arm do
      sha256 "96fca68fe28f58a71f1774b2da9bb732aa6d3f0db4b9597ac9b91d1a4bae71a9"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_darwin_arm64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "322ae020b3bdca50ac86ab7b4035e900a31be732304896b972513b8dd824af3c"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_linux_amd64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
    on_arm do
      sha256 "9a94a60b35d5688f0c059b170f4f50d3a8efee0bf10400340754184606358dec"
      url "https://github.com/quantcli/liftoff-export-cli/releases/download/v#{version}/liftoff-export_linux_arm64.zip",
        verified: "github.com/quantcli/liftoff-export-cli"
    end
  end

  name "liftoff-export"
  desc "CLI tool to export and analyze workout data from the Liftoff fitness app"
  homepage "https://github.com/quantcli/liftoff-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "liftoff-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/liftoff-export"]
    end
  end

  # No zap stanza required

end
