# This file was generated by GoReleaser. DO NOT EDIT.
cask "withings-export" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_darwin_amd64.zip",
        verified: "github.com/quantcli/withings-export-cli"
      sha256 "432910353a7ec0ea3cdb17a28b056049956a7c8a3cdda33c0631dc55b9f7f965"
    end
    on_arm do
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_darwin_arm64.zip",
        verified: "github.com/quantcli/withings-export-cli"
      sha256 "a1f71cbd94018d670a7d9df9193061706a062f732792b327424a18df28fb4064"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_linux_amd64.zip",
        verified: "github.com/quantcli/withings-export-cli"
      sha256 "90a619d3105d9773ac384e32cce3c9aca2ceebe83539502fb1f9abc498bf3689"
    end
    on_arm do
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_linux_arm64.zip",
        verified: "github.com/quantcli/withings-export-cli"
      sha256 "cff7184a0256d554f9d0768df5a1207890d7b08fbf657ed06c3f91643b522e8d"
    end
  end

  name "withings-export"
  desc "CLI to export health data from Withings (scales, watches, activity, sleep)"
  homepage "https://github.com/quantcli/withings-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "withings-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/withings-export"]
    end
  end

  # No zap stanza required

end
