# This file was generated by GoReleaser. DO NOT EDIT.
cask "withings-export" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_darwin_amd64.zip",
        verified: "github.com/quantcli/withings-export-cli"
      sha256 "aa8769d604f978106359bd73ffeab51de4367cf812c41d2df9d4563cc1ca7fc2"
    end
    on_arm do
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_darwin_arm64.zip",
        verified: "github.com/quantcli/withings-export-cli"
      sha256 "c815117610ea0f4243cc8e4ae94667fb21f60ad8df7aa98f15f7695516cdc080"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_linux_amd64.zip",
        verified: "github.com/quantcli/withings-export-cli"
      sha256 "febc8e6326207b5ed98616085bf4dd8ba6b1eec2be660ea15f5799418c2b9389"
    end
    on_arm do
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_linux_arm64.zip",
        verified: "github.com/quantcli/withings-export-cli"
      sha256 "c34d6d9dce3cec925e5278e516b495ca165582bb3083ff475f9681ce93f0a873"
    end
  end

  name "withings-export"
  desc "CLI to export health data from Withings (scales, watches, activity, sleep)"
  homepage "https://github.com/quantcli/withings-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "withings-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/withings-export"]
    end
  end

  # No zap stanza required

end
