# This file was generated by GoReleaser. DO NOT EDIT.
cask "withings-export" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "7999c3f32f090feda3f38b4fe9e418e74f0c8089c071aa8d8b7d1cd8a50ddd84"
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_darwin_amd64.zip",
        verified: "github.com/quantcli/withings-export-cli"
    end
    on_arm do
      sha256 "558a6695ad433be0061005d80f26d8658a6b53f173a7335ee8a25966c43b6d13"
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_darwin_arm64.zip",
        verified: "github.com/quantcli/withings-export-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "4ec5a9f8d91bce13aff58ff45c3cc58972b196f2d8324151b10004d537417c0d"
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_linux_amd64.zip",
        verified: "github.com/quantcli/withings-export-cli"
    end
    on_arm do
      sha256 "e3652dc85fed862486b4b36203ae086ee7b251a89a4b39ec636a69bf691fb5fb"
      url "https://github.com/quantcli/withings-export-cli/releases/download/v#{version}/withings-export_linux_arm64.zip",
        verified: "github.com/quantcli/withings-export-cli"
    end
  end

  name "withings-export"
  desc "CLI to export health data from Withings (scales, watches, activity, sleep)"
  homepage "https://github.com/quantcli/withings-export-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "withings-export"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/withings-export"]
    end
  end

  # No zap stanza required

end
